[tox]
requires =
    tox>=4.28
env_list =
    local
    testpypi
    pypi

[testenv]
description = Installationstest
skip_install = true
setenv =
    PACKAGE_NAME = peastb
    PACKAGE_VERSION = 0.1.0a4

deps =
    pytest

commands =
    pytest tests_installation

[testenv:local]
commands_pre =
    python -m pip install dist/{env:PACKAGE_NAME}-{env:PACKAGE_VERSION}-py3-none-any.whl

[testenv:testpypi]
commands_pre =
    python -m pip install \
        --index-url https://test.pypi.org/simple \
        --extra-index-url https://pypi.org/simple \
        {env:PACKAGE_NAME}=={env:PACKAGE_VERSION}

[testenv:pypi]
commands_pre =
    python -m pip install \
        {env:PACKAGE_NAME}=={env:PACKAGE_VERSION}